name: Docker Image CI

on:
  push:
    branches: [ API ]
  pull_request:
    branches: [ API ]

permissions:
  contents: read

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: |
          cp env.docker .env
          docker compose -f docker-compose.yml up -d --wait
      - name: "Test server"
        run: docker exec -it aptrs-1 cd /home /home/aptrs/APTRS/APTRS && python3 manange.py test